version: "3.9"

networks:
  e_pharmacy-compose-network:
    name: ${DOCKER_PROJECT}_${APP_ENV}-compose-network
    driver: bridge
    external: True

volumes:
  mysql_volume:
    name: ${DOCKER_PROJECT}_${APP_ENV}_mysql_volume
  web_storage_volume:
    name: ${DOCKER_PROJECT}_${APP_ENV}_web_storage_volume
  web_global_log_volume:
    name: ${DOCKER_PROJECT}_${APP_ENV}_web_global_log_volume
  redis_volume:
    name: ${DOCKER_PROJECT}_${APP_ENV}_redis_volume
  insight_static_volume:
    name: ${DOCKER_PROJECT}_${APP_ENV}_insight_static_volume

services:
  mysql_db:
    container_name: ${DOCKER_PROJECT}-mysql-${APP_ENV}
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_TEST_DATABASE: ${MYSQL_TEST_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_READONLY_USER: ${MYSQL_READONLY_USER}
      MYSQL_READONLY_PASSWORD: ${MYSQL_READONLY_PASSWORD}
      MYSQL_TEST_USERNAME: ${MYSQL_TEST_USERNAME}
      MYSQL_TEST_PASSWORD: ${MYSQL_TEST_PASSWORD}
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./docker/mysql-add-test-db.sh:/docker-entrypoint-initdb.d/01-add-test-db.sh
    networks:
      - e_pharmacy-compose-network
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  redis_master:
    container_name: ${DOCKER_PROJECT}-redis-master-${APP_ENV}
    image: redis/redis-stack-server:7.2.0-RC2
    command: redis-server /etc/redis/redis.conf
    restart: unless-stopped
    volumes:
      - ./docker/etc/redis:/etc/redis/
      - redis_volume:/data/
    networks:
      - e_pharmacy-compose-network
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli --pass $REDIS_PASSWORD ping) = PONG ]"]
      retries: 3
      timeout: 5s

  rabbitmq:
    container_name: ${DOCKER_PROJECT}-rabbitmq-${APP_ENV}
    image: autozone1/rabbitmq:3.9.29-management-plus-alpine
    networks:
      - e_pharmacy-compose-network
    restart: unless-stopped
    volumes:
      - ./docker/etc/rabbitmq:/etc/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      retries: 3
      timeout: 5s

  web:
    container_name: ${DOCKER_PROJECT}-web-${APP_ENV}
    networks:
      - e_pharmacy-compose-network
    volumes:
      - web_storage_volume:/var/www/storage
      - web_global_log_volume:/var/log
    depends_on:
      mysql_db:
        condition: service_healthy
      redis_master:
        condition: service_healthy
      rabbitmq:
          condition: service_healthy
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL:  http://localhost:${WEB_PORT}
      
      LOG_CHANNEL: stack
      LOG_DEPRECATIONS_CHANNEL: null
      LOG_LEVEL: debug

      DESTROY_DB: ${DESTROY_DB}
      SEED_DB: ${SEED_DB}
      DB_CONNECTION: mysql
      DB_HOST: ${DOCKER_PROJECT}-mysql-${APP_ENV}
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      BROADCAST_DRIVER: log
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
      FILESYSTEM_DISK: local
      SESSION_LIFETIME: 120

      REDIS_HOST: ${DOCKER_PROJECT}-redis-master-${APP_ENV}
      REDIS_PORT: 6379
      REDIS_DB: 3
      REDIS_CACHE_DB: 4
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      MQ_HOST: ${DOCKER_PROJECT}-rabbitmq-${APP_ENV}
      MQ_VHOST: ${RABBITMQ_VHOST}
      MQ_PORT: 5672
      MQ_USER: ${RABBITMQ_USERNAME}
      MQ_PASSWORD: ${RABBITMQ_PASSWORD}

      MAIL_MAILER: smtp
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: "hello@example.com"
      MAIL_FROM_NAME: "${APP_NAME}"

      TIMEOUT_BACKUP: ${TIMEOUT_BACKUP}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
    healthcheck:
      test: ['CMD-SHELL', 'curl --fail http://localhost:${WEB_PORT} || exit 1']
      timeout: 15s
      retries: 10

  consumer:
    networks:
      - e_pharmacy-compose-network
    volumes:
      - web_storage_volume:/var/www/storage
      - web_global_log_volume:/var/log
    depends_on:
      mysql_db:
        condition: service_healthy
      redis_master:
        condition: service_healthy
      rabbitmq:
          condition: service_healthy

    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: http://localhost
      
      LOG_CHANNEL: stack
      LOG_DEPRECATIONS_CHANNEL: null
      LOG_LEVEL: debug

      DESTROY_DB: ${DESTROY_DB}
      SEED_DB: ${SEED_DB}
      DB_CONNECTION: mysql
      DB_HOST: ${DOCKER_PROJECT}-mysql-${APP_ENV}
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      BROADCAST_DRIVER: log
      FILESYSTEM_DISK: local
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
      SESSION_LIFETIME: 120

      REDIS_HOST: ${DOCKER_PROJECT}-redis-master-${APP_ENV}
      REDIS_PORT: 6379
      REDIS_DB: 3
      REDIS_CACHE_DB: 4
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      MQ_HOST: ${DOCKER_PROJECT}-rabbitmq-${APP_ENV}
      MQ_VHOST: ${RABBITMQ_VHOST}
      MQ_PORT: 5672
      MQ_USER: ${RABBITMQ_USERNAME}
      MQ_PASSWORD: ${RABBITMQ_PASSWORD}

      MAIL_MAILER: smtp
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: "hello@example.com"
      MAIL_FROM_NAME: "${APP_NAME}"

      TIMEOUT_BACKUP: ${TIMEOUT_BACKUP}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}

  worker:
      networks:
        - e_pharmacy-compose-network
      volumes:
        - web_storage_volume:/var/www/storage
        - web_global_log_volume:/var/log
      depends_on:
        mysql_db:
          condition: service_healthy
        redis_master:
          condition: service_healthy
        rabbitmq:
            condition: service_healthy

      environment:
        APP_NAME: ${APP_NAME}
        APP_ENV: ${APP_ENV}
        APP_KEY: ${APP_KEY}
        APP_DEBUG: ${APP_DEBUG}
        APP_URL: http://localhost
        
        LOG_CHANNEL: stack
        LOG_DEPRECATIONS_CHANNEL: null
        LOG_LEVEL: debug

        DESTROY_DB: ${DESTROY_DB}
        SEED_DB: ${SEED_DB}
        DB_CONNECTION: mysql
        DB_HOST: ${DOCKER_PROJECT}-mysql-${APP_ENV}
        DB_PORT: 3306
        DB_DATABASE: ${MYSQL_DATABASE}
        DB_USERNAME: ${MYSQL_USER}
        DB_PASSWORD: ${MYSQL_PASSWORD}
        BROADCAST_DRIVER: log
        FILESYSTEM_DISK: local
        CACHE_DRIVER: redis
        QUEUE_CONNECTION: redis
        SESSION_DRIVER: redis
        SESSION_LIFETIME: 120

        REDIS_HOST: ${DOCKER_PROJECT}-redis-master-${APP_ENV}
        REDIS_PORT: 6379
        REDIS_DB: 3
        REDIS_CACHE_DB: 4
        REDIS_PASSWORD: ${REDIS_PASSWORD}

        MQ_HOST: ${DOCKER_PROJECT}-rabbitmq-${APP_ENV}
        MQ_VHOST: ${RABBITMQ_VHOST}
        MQ_PORT: 5672
        MQ_USER: ${RABBITMQ_USERNAME}
        MQ_PASSWORD: ${RABBITMQ_PASSWORD}

        MAIL_MAILER: smtp
        MAIL_HOST: mailpit
        MAIL_PORT: 1025
        MAIL_USERNAME: null
        MAIL_PASSWORD: null
        MAIL_ENCRYPTION: null
        MAIL_FROM_ADDRESS: "hello@example.com"
        MAIL_FROM_NAME: "${APP_NAME}"

        TIMEOUT_BACKUP: ${TIMEOUT_BACKUP}
        FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
        FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
        FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}

  phpmyadmin:
    container_name: ${DOCKER_PROJECT}-myadmin-${APP_ENV}
    image: phpmyadmin:5.2.1-apache
    restart: unless-stopped
    environment:
      PMA_HOST: ${DOCKER_PROJECT}-mysql-${APP_ENV}
    networks:
      - e_pharmacy-compose-network
    depends_on:
      mysql_db:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -Ss --fail http://localhost/robots.txt || exit 1']
      timeout: 10s
      retries: 10

  redisinsight:
    container_name: ${DOCKER_PROJECT}-redisinsight-${APP_ENV}
    image: 'redislabs/redisinsight:1.13.1'
    restart: unless-stopped
    volumes:
      - insight_static_volume:/app/redisinsight/static
    networks:
      - e_pharmacy-compose-network
    depends_on:
      redis_master:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl --fail http://localhost:8001/healthcheck/ || exit 1']
      timeout: 20s
      retries: 10

  nginx:
      container_name: ${DOCKER_PROJECT}-nginx-${APP_ENV}
      restart: unless-stopped
      environment:
        NGINX_USER: ${NGINX_USER}
        NGINX_PASSWORD: ${NGINX_PASSWORD}
        NGINX_WEB_HOST: ${DOCKER_PROJECT}-web-${APP_ENV}
        NGINX_MYADMIN_HOST: ${DOCKER_PROJECT}-myadmin-${APP_ENV}
        NGINX_MYADMIN_PORT: 80
        NGINX_INSIGHT_HOST: ${DOCKER_PROJECT}-redisinsight-${APP_ENV}
        NGINX_INSIGHT_PORT: 8001
        STATIC_ROOT: /static
        INSIGHT_STATIC_ROOT: /static/insight
        NGINX_RABBITMQ_HOST: ${DOCKER_PROJECT}-rabbitmq-${APP_ENV}
        NGINX_RABBITMQ_PORT: 15672
      networks:
        - e_pharmacy-compose-network
      volumes:
        - insight_static_volume:/static/insight/
      depends_on:
        phpmyadmin:
          condition: service_healthy
        rabbitmq:
          condition: service_healthy
        redisinsight:
          condition: service_healthy
        web:
          condition: service_healthy
