version: "3.9"

services:
  mysql_db:
    ports:
      - "20001:3306"

  phpmyadmin:
    environment:
      PMA_ABSOLUTE_URI: 'http://localhost:20002/apps/myadmin/'

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile-system
      target: dev
    restart: always
    entrypoint: docker/docker-entrypoint.sh
    volumes:
        - .:/var/www

  consumer:
    build:
      context: .
      dockerfile: docker/Dockerfile-system
      target: consumer
    container_name: ${DOCKER_PROJECT}-consumer-${APP_ENV}
    restart: always
    entrypoint: docker/consume.sh
    # You need to override command when override entrypoint according to this github issue https://github.com/docker/compose/issues/3140
    command: "php artisan mq:consume"
    volumes:
        - .:/var/www

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile-system
      target: consumer
    container_name: ${DOCKER_PROJECT}-worker-${APP_ENV}
    restart: always
    entrypoint: docker/consume.sh
    # You need to override command when override entrypoint according to this github issue https://github.com/docker/compose/issues/3140
    command: "php artisan queue:work"
    volumes:
        - .:/var/www

  redisinsight:
    environment:
      RITRUSTEDORIGINS: 'http://localhost:80,http://localhost:20002'
      RIPROXYENABLE: 1

  nginx:
      build:
        context: .
        dockerfile: ./docker/Dockerfile-nginx
      environment:
        NGINX_SERVER_NAME: localhost
        NGINX_WEB_PORT: 8080
      ports:
        - "20002:80"

